backend:
  name: github
  repo: Hoodlum-Z/my-gridsome-site

media_folder: "/static/images/uploads"
public_folder: "/images/uploads"

publish_mode: "editorial_workflow"

collections:
  - label: "Posts"
    name:  "posts"
    folder: "posts"
    create: true
    preview_path: "posts/{{slug}}"
    slug: "{{slug}}"
    preview_path_date_field: "updated_on"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}   
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Featured Post", name: "featured_post", widget: "boolean", default: false}
      - label: "Featured Image"
        name: "featured_image"
        widget: "object"
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Alt text", name: "alt", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags (comma seperated)", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}